### ISSUE TITLE
Do fx sync 4 fos work standalone?

### ISSUE THREAD

**Issue by mautematico** [cat-in-136/fx-sync-4-fos#4]
Do this app work standalone, or may be it needs a _bridge_ between Sync servers and the device?

**Comment by cat-in-136** [comment]
You have only to enter an email address and the password of the [Firefox account](https://accounts.firefox.com/).

This app is now just a _viewer_. So you have to create an account and use Sync on Desktop or Android.

**Comment by mautematico** [comment]
What I am asking is: fx sync makes a _direct_ connection to Sync servers, or makes a connection via some bridge/proxy?

btw, there are some folks on mozilla working on a gaia app. :)
https://bugzilla.mozilla.org/show_bug.cgi?id=824026

**Comment by mautematico** [comment]
May be you can give them a hand?

**Comment by cat-in-136** [comment]
No bridge.
This app directly connects to the server using [node-fx-sync](https://github.com/cat-in-136/node-fx-sync).

**Comment by cat-in-136** [comment]
I know some folks on mozilla.
But implementation process is too slow for me and there is no document.

So, I created a simple viewer. It's my first Firefox OS app.

**Comment by cat-in-136** [comment]
I have added this question to README.md in changeset 766b4c8.

**Comment by mautematico** [comment]
Thank you!
